package:
  name: mitgcm
  version: "0.1.2"
 
source:
  git_rev: 0.1.2
  git_url: https://bitbucket.org/edoddridge/mitgcm.git
 
requirements:
  build:
    - python
    - setuptools
    - scipy
    - numpy
    - numba
    - netcdf4
    - matplotlib
  run:
    - python
    - scipy
    - numpy
    - numba
    - netcdf4
    - matplotlib

about:
  home: https://bitbucket.org/edoddridge/mitgcm
  license: MIT
